[package]
name = "see"
version = "0.1.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
oof = { path = "../oof" }
bonsai = { path = "../bonsai", default-features = false, features = ["u128"] }
interface = { path = "interface" }
