[package]
name = "proof"
version = "0.1.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
bonsai = { path = "../../bonsai", default-features = false, features = ["u128"] }
oof = { path = "../../oof" }

